import datetime
# Import UserMixin and RoleMixin from Flask-Security
from flask_security import UserMixin, RoleMixin
# Import db instance from your database setup file
from applications.database import db

# Association Table for User-Role Many-to-Many relationship (Required by Flask-Security)
user_roles = db.Table('user_roles',
    db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
    db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
)

class Role(db.Model, RoleMixin):
    """
    Represents a user role (e.g., 'admin', 'user').
    Inherits RoleMixin for Flask-Security compatibility.
    """
    __tablename__ = 'role'

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False) # Role name (e.g., 'admin')
    description = db.Column(db.String(255)) # Optional description

    def __repr__(self):
        return f'<Role {self.name}>'

class User(db.Model, UserMixin):
    """
    Represents a user account.
    Inherits UserMixin for Flask-Security compatibility.
    """
    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True)
    # Use 'email' for login if preferred by Flask-Security config, otherwise 'username'
    # Check your user_datastore setup if using email vs username. Assuming username for now.
    username = db.Column(db.String(80), unique=True, nullable=False)
    # IMPORTANT: Field must be named 'password' for Flask-Security's default hashing/verification
    password = db.Column(db.String(255), nullable=False) # Stores the hash generated by Flask-Security
    email = db.Column(db.String(120), unique=True, nullable=True) # Unique email is good practice
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow) # Track creation time
    # Required fields for Flask-Security:
    active = db.Column(db.Boolean()) # Is the user account active?
    fs_uniquifier = db.Column(db.String(64), unique=True, nullable=False) # Security stamp

    # Relationship to Role model via the user_roles association table
    roles = db.relationship('Role', secondary=user_roles,
                            backref=db.backref('users', lazy='dynamic'))

    # Relationship to Watchlist items (One-to-Many)
    watchlist_items = db.relationship('Watchlist', backref='owner', lazy=True, cascade='all, delete-orphan')

    # REMOVED custom set_password and check_password methods.
    # Flask-Security (via user_datastore.create_user and utils.verify_password) handles hashing.

    def __repr__(self):
        return f'<User {self.username}>'

class Watchlist(db.Model):
    """
    Represents a stock ticker saved by a user.
    """
    __tablename__ = 'watchlist'

    id = db.Column(db.Integer, primary_key=True)
    # Foreign Key linking back to the User who owns this item
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    ticker = db.Column(db.String(10), nullable=False) # Stock symbol
    notes = db.Column(db.String(200), nullable=True) # Optional user notes
    added_at = db.Column(db.DateTime, default=datetime.datetime.utcnow) # Track when added

    # Ensure a specific user cannot add the same ticker multiple times
    __table_args__ = (db.UniqueConstraint('user_id', 'ticker', name='_user_ticker_uc'),)

    def to_dict(self):
        """Helper method to convert object to dictionary for JSON serialization."""
        return {
            "id": self.id,
            "ticker": self.ticker,
            "notes": self.notes if self.notes else "",
            "user_id": self.user_id,
            "added_at": self.added_at.isoformat() if self.added_at else None
        }

    def __repr__(self):
        return f'<Watchlist Ticker:{self.ticker} UserID:{self.user_id}>'


class PortfolioHolding(db.Model):
    """
    Represents a stock holding in a user's portfolio.
    Tracks quantity, purchase price, and current value.
    """
    __tablename__ = 'portfolio_holding'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    symbol = db.Column(db.String(20), nullable=False)  # Stock ticker (e.g., 'TCS', 'RELIANCE')
    quantity = db.Column(db.Float, nullable=False)  # Number of shares owned
    purchase_price = db.Column(db.Float, nullable=False)  # Average purchase price per share
    current_value = db.Column(db.Float, nullable=False)  # Current value (auto-updated)
    added_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    # Ensure unique holding per user per symbol
    __table_args__ = (db.UniqueConstraint('user_id', 'symbol', name='_user_symbol_holding_uc'),)

    def to_dict(self):
        return {
            'id': self.id,
            'symbol': self.symbol,
            'quantity': self.quantity,
            'purchase_price': self.purchase_price,
            'current_value': self.current_value,
            'total_invested': round(self.quantity * self.purchase_price, 2),
            'gain_loss': round(self.current_value - (self.quantity * self.purchase_price), 2),
            'gain_loss_percent': round(((self.current_value - (self.quantity * self.purchase_price)) / (self.quantity * self.purchase_price) * 100), 2) if (self.quantity * self.purchase_price) != 0 else 0,
            'added_at': self.added_at.isoformat() if self.added_at else None,
        }

    def __repr__(self):
        return f'<PortfolioHolding {self.symbol} Qty:{self.quantity} UserID:{self.user_id}>'


class PortfolioSnapshot(db.Model):
    """
    Historical snapshot of portfolio value for performance tracking.
    Stores total portfolio value at a specific point in time.
    """
    __tablename__ = 'portfolio_snapshot'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    total_value = db.Column(db.Float, nullable=False)  # Total portfolio value at this snapshot
    snapshot_date = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    
    # Ensure one snapshot per user per day (approximately)
    __table_args__ = (db.Index('_user_date_idx', 'user_id', 'snapshot_date'),)

    def to_dict(self):
        return {
            'id': self.id,
            'total_value': self.total_value,
            'snapshot_date': self.snapshot_date.isoformat() if self.snapshot_date else None,
        }

    def __repr__(self):
        return f'<PortfolioSnapshot UserID:{self.user_id} Value:{self.total_value} Date:{self.snapshot_date}>'


class InvestmentGoal(db.Model):
    """
    Represents a financial goal for the user.
    Tracks target amount, target date, and investment contribution requirements.
    """
    __tablename__ = 'investment_goal'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    goal_name = db.Column(db.String(100), nullable=False)  # e.g., "House", "Retirement", "Car"
    description = db.Column(db.String(500), nullable=True)
    target_amount = db.Column(db.Float, nullable=False)  # Amount needed (in ₹)
    current_amount = db.Column(db.Float, default=0)  # Amount saved so far
    target_date = db.Column(db.DateTime, nullable=False)  # Target completion date
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    def to_dict(self):
        import datetime as dt
        now = datetime.datetime.utcnow()
        time_remaining = (self.target_date - now).days
        progress_percent = round((self.current_amount / self.target_amount * 100), 2) if self.target_amount != 0 else 0
        months_remaining = max(1, time_remaining // 30)
        monthly_needed = round((self.target_amount - self.current_amount) / months_remaining, 2) if months_remaining > 0 else 0

        return {
            'id': self.id,
            'goal_name': self.goal_name,
            'description': self.description,
            'target_amount': self.target_amount,
            'current_amount': self.current_amount,
            'target_date': self.target_date.isoformat() if self.target_date else None,
            'progress_percent': progress_percent,
            'amount_remaining': round(self.target_amount - self.current_amount, 2),
            'days_remaining': time_remaining,
            'months_remaining': months_remaining,
            'monthly_contribution_needed': monthly_needed,
            'created_at': self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self):
        return f'<InvestmentGoal {self.goal_name} UserID:{self.user_id} Target:₹{self.target_amount}>'

